communication:
  port: /dev/serial0
  baudrate: 5
  typecom: 0
general:
  loc: 0
  scan: 2
database:
  url: 'https://sensors-xxolsllgga-as.a.run.app'
  timeInterval: 10
boxes:
  - name: box1
    address: 1
    channel:
    - ch: 1
      sensorID: 25
      display: 1
      input: 7
      pvs: 0
      pvf: 1
      dp: 1
      c/f: 0
      abs: 0
      inv: 0    
      slh: 8500
      sll: 63537
    - ch: 2
      sensorID: 26
      display: 1
      input: 7
      pvs: 0
      pvf: 1
      dp: 1
      c/f: 0
      abs: 0
      inv: 0    
      slh: 8500
      sll: 63537