communication:
  port: com10
  baudrate: 5
  typecom: 0
general:
  loc: 0
  scan: 10
boxes:
  - name: box1
    address: 1
    channel: 
    - ch: 1
      display: 1
      input: 7
      pvs: 0
      pvf: 1
      dp: 1
      c/f: 0
      abs: 0
      inv: 0
      inh: null
      inl: null
      slh: 8500
      sll: 63537
      alf: 0
      alh: 0
      all: 0
      hys: 0
      ton: 0
      toff: 0
      opr: 0
  - name: box2
    address: 1
    channel: 
    - ch: 4
      display: 1
      input: 7
      pvs: 0
      pvf: 1
      dp: 1
      c/f: 0
      abs: 0
      inv: 0
      inh: null
      inl: null
      slh: 8500
      sll: 63537
      alf: 0
      alh: 0
      all: 0
      hys: 0
      ton: 0
      toff: 0
      opr: 0